### Encoding Categorical Data

#### Lable Encoding - Odinal Data
ordered data

In [1]:
import pandas as pd
df = pd.read_csv("./customer.csv")
df.sample(3)

    age  gender   review education purchased
1    68  Female     Poor        UG        No
42   30  Female     Good        PG       Yes
20   57  Female  Average    School       Yes

In [3]:
df["gender"].unique(),df["review"].unique(),df["education"].unique(),df["purchased"].unique()

(array(['Female', 'Male'], dtype=object),
 array(['Average', 'Poor', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object),
 array(['No', 'Yes'], dtype=object))

In [ ]:
#here review, education and purchased are order data

from sklearn.model_selection import train_test_split

X = df.iloc[:,2:4]
Y = df.iloc[:,4:]

X_train: pd.DataFrame
X_test: pd.DataFrame
Y_train: pd.Series
Y_test: pd.Series

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=45)

In [13]:
X_train.head(5)

   review education
25   Good    School
46   Poor        PG
48   Good        UG
45   Poor        PG
41   Good        PG

In [ ]:
#do encoding
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories= [ ['Poor', 'Average', 'Good'] , ['School', 'UG', 'PG']] )
#here categories belong to set order lower to hig for all cols

oe.fit(X_train)

X_train_tranformed = oe.transform(X_train)
X_test_tranformed = oe.transform(X_test)

X_train_tranformed_df = pd.DataFrame(X_train_tranformed, columns=X_train.columns)
X_test_tranformed_df = pd.DataFrame(X_test_tranformed, columns=X_test.columns)

X_train_tranformed_df.head(5) #order set :)

   review  education
0     2.0        0.0
1     0.0        2.0
2     2.0        1.0
3     0.0        2.0
4     2.0        2.0

In [17]:
# for output use LabelEncoding 
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()
le.fit(Y_train)

Y_train_tranformed = le.transform(Y_train)
Y_test_tranformed = le.transform(Y_test)

Y_train_tranformed_df = pd.DataFrame(Y_train_tranformed, columns=Y_train.columns)
Y_test_tranformed_df = pd.DataFrame(Y_test_tranformed, columns=Y_test.columns)

Y_train_tranformed_df.head(5) #order set :)

c:\Users\devan\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:93: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\devan\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
c:\Users\devan\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

   purchased
0          0
1          0
2          1
3          1
4          1

In [ ]:
Y_train.head(5) # No - 0 and Yes - 1

   purchased
25        No
46        No
48       Yes
45       Yes
41       Yes