In [19]:
import pandas as pd
data = pd.read_csv("after01.csv")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       14 non-null     object
 1   score      14 non-null     float64
 2   city       14 non-null     object
 3   placement  14 non-null     float64
dtypes: float64(2), object(2)
memory usage: 576.0+ bytes

type 1 - label encoding

In [20]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

#hear we only do on true/false - 0/1
data["placement"] = le.fit_transform(data["placement"])
data

      name      score       city  placement
0    Aarav  85.600000      Delhi          1
1     Isha  75.954545     Mumbai          0
2    Rohan  91.200000    Chennai          1
3    Meera  67.800000       Pune          0
4    Kabir  88.500000  Hyderabad          1
5   Simran  75.954545    Chennai          1
6    Arjun  59.300000    Kolkata          0
7      Dev  94.700000  Bangalore          1
8   Ritika  63.500000    Chennai          0
9    Kunal  78.400000       Pune          1
10    Neha  81.900000  Hyderabad          0
11     Raj  55.200000    Chennai          0
12   Priya  75.954545    Kolkata          1
13  Aditya  69.400000      Delhi          0

type-2 one-hot method

In [21]:

data = pd.get_dummies(data=data, columns=["city"], dtype=int)
data

,name,score,placement,city_Bangalore,city_Chennai,city_Delhi,city_Hyderabad,city_Kolkata,city_Mumbai,city_Pune
0,Aarav,85.600000,1,0,0,1,0,0,0,0
1,Isha,75.954545,0,0,0,0,0,0,1,0
2,Rohan,91.200000,1,0,1,0,0,0,0,0
3,Meera,67.800000,0,0,0,0,0,0,0,1
4,Kabir,88.500000,1,0,0,0,1,0,0,0
5,Simran,75.954545,1,0,1,0,0,0,0,0
6,Arjun,59.300000,0,0,0,0,0,1,0,0
7,Dev,94.700000,1,1,0,0,0,0,0,0
8,Ritika,63.500000,0,0,1,0,0,0,0,0
9,Kunal,78.400000,1,0,0,0,0,0,0,1
10,Neha,81.900000,0,0,0,0,1,0,0,0
11,Raj,55.200000,0,0,1,0,0,0,0,0
12,Priya,75.954545,1,0,0,0,0,1,0,0
13,Aditya,69.400000,0,0,0,1,0,0,0,0

In [23]:
# export data
data.to_csv("after02.csv", index=False)