In [28]:
import pandas as pd
data = pd.read_csv("after02.csv")
ndata = data.drop(columns=["name"])
ndata.head(1)

,score,placement,city_Bangalore,city_Chennai,city_Delhi,city_Hyderabad,city_Kolkata,city_Mumbai,city_Pune
0,85.6,1,0,0,1,0,0,0,0

type-1 standard scaling

In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

scaled = sc.fit_transform(ndata)

pd.DataFrame(scaled, columns=ndata.columns)

,score,placement,city_Bangalore,city_Chennai,city_Delhi,city_Hyderabad,city_Kolkata,city_Mumbai,city_Pune
0,8.394684e-01,1.0,-0.277350,-0.632456,2.449490,-0.408248,-0.408248,-0.277350,-0.408248
1,-1.236807e-15,-1.0,-0.277350,-0.632456,-0.408248,-0.408248,-0.408248,3.605551,-0.408248
2,1.326851e+00,1.0,-0.277350,1.581139,-0.408248,-0.408248,-0.408248,-0.277350,-0.408248
3,-7.097108e-01,-1.0,-0.277350,-0.632456,-0.408248,-0.408248,-0.408248,-0.277350,2.449490
4,1.091863e+00,1.0,-0.277350,-0.632456,-0.408248,2.449490,-0.408248,-0.277350,-0.408248
5,-1.236807e-15,1.0,-0.277350,1.581139,-0.408248,-0.408248,-0.408248,-0.277350,-0.408248
6,-1.449487e+00,-1.0,-0.277350,-0.632456,-0.408248,-0.408248,2.449490,-0.277350,-0.408248
7,1.631464e+00,1.0,3.605551,-0.632456,-0.408248,-0.408248,-0.408248,-0.277350,-0.408248
8,-1.083951e+00,-1.0,-0.277350,1.581139,-0.408248,-0.408248,-0.408248,-0.277350,-0.408248
9,2.128341e-01,1.0,-0.277350,-0.632456,-0.408248,-0.408248,-0.408248,-0.277350,2.449490
10,5.174480e-01,-1.0,-0.277350,-0.632456,-0.408248,2.449490,-0.408248,-0.277350,-0.408248
11,-1.806321e+00,-1.0,-0.277350,1.581139,-0.408248,-0.408248,-0.408248,-0.277350,-0.408248
12,-1.236807e-15,1.0,-0.277350,-0.632456,-0.408248,-0.408248,2.449490,-0.277350,-0.408248
13,-5.704587e-01,-1.0,-0.277350,-0.632456,2.449490,-0.408248,-0.408248,-0.277350,-0.408248

type - 2 MinMax scaling

In [32]:
from sklearn.preprocessing import MinMaxScaler
mc = MinMaxScaler()

mscaled = mc.fit_transform(ndata)

# i like this scale :) - so i store
ndata = pd.DataFrame(mscaled, columns=ndata.columns)
ndata

,score,placement,city_Bangalore,city_Chennai,city_Delhi,city_Hyderabad,city_Kolkata,city_Mumbai,city_Pune
0,0.769620,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.525432,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.911392,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.318987,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.843038,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5,0.525432,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
6,0.103797,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
7,1.000000,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.210127,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
9,0.587342,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10,0.675949,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
11,0.000000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
12,0.525432,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
13,0.359494,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [31]:
# export data
ndata.to_csv("after03.csv", index=False)